language: node_js
node_js: 12.18.2
git:
  depth: false
jobs:
  include:
  - stage: Pre-release
    if: branch = master
    before_deploy:
    - git checkout master
    deploy:
    - provider: script
      script: bash ./ci-scripts/publish-rc.sh
      skip_cleanup: true